### ISSUE TITLE
build failing for PLATFORM=p4

### ISSUE THREAD

**Issue by mdivyamohan** [Azure/sonic-buildimage#2591]
I am trying to build sonic image with instructions given [here](https://github.com/Azure/sonic-buildimage/blob/master/README.md).

I am using debian stretch environment, and PLATFORM is set as p4.
Compilation is failing with error:
```
make: *** No rule to make target 'target/debs/python-p4-hlir_0.9.36-1_all.deb', needed by 'target/debs/python-p4-hlir_0.9.36-1_all.deb-install'.  Stop.
Makefile.work:128: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/divym/sonic/sonic-buildimage'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
```
The [jenkins build](https://sonic-jenkins.westus2.cloudapp.azure.com/job/p4/job/buildimage-p4-all/964/console) also seems to be failing with same error.

Do we have any workaround for this issue?

**Comment by nathanalderson** [comment]
I believe the issue @mdivyamohan mentions was introduced by #2519, first built in [build 950](https://sonic-jenkins.westus2.cloudapp.azure.com/job/p4/job/buildimage-p4-all/950/).

Prior to that, a nearly year-long standing issue existed:

```
g++ -I/usr/include/sai -I. -std=c++11 -c src/switch_sai_rpc_server.cpp -o src/obj/switch_sai_rpc_server.o -I/usr/include/sai -I. -std=c++11 -I./src/gen-cpp
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_fdb_entry(const switch_sai::sai_thrift_fdb_entry_t&, sai_fdb_entry_t*)':
src/switch_sai_rpc_server.cpp:219:18: error: 'sai_fdb_entry_t' has no member named 'bv_id'
       fdb_entry->bv_id = (sai_object_id_t) thrift_fdb_entry.bv_id;
                  ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_port_attributes(const std::vector<switch_sai::sai_thrift_attribute_t>&, sai_attribute_t*, sai_object_id_t**)':
src/switch_sai_rpc_server.cpp:245:20: error: 'SAI_PORT_ATTR_PKT_TX_ENABLE' was not declared in this scope
               case SAI_PORT_ATTR_PKT_TX_ENABLE:
                    ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_fdb_flush_attributes(const std::vector<switch_sai::sai_thrift_attribute_t>&, sai_attribute_t*)':
src/switch_sai_rpc_server.cpp:331:20: error: 'SAI_FDB_FLUSH_ATTR_BV_ID' was not declared in this scope
               case SAI_FDB_FLUSH_ATTR_BV_ID:
                    ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_lag_attributes(const std::vector<switch_sai::sai_thrift_attribute_t>&, sai_attribute_t*)':
src/switch_sai_rpc_server.cpp:435:20: error: 'SAI_LAG_ATTR_PORT_VLAN_ID' was not declared in this scope
               case SAI_LAG_ATTR_PORT_VLAN_ID:
                    ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_hostif_attributes(sai_attribute_t*, const std::vector<switch_sai::sai_thrift_attribute_t>&) const':
src/switch_sai_rpc_server.cpp:522:94: error: 'SAI_HOSTIF_NAME_SIZE' was not declared in this scope
                   std::memcpy(attr_list[i].value.chardata, attribute.value.chardata.c_str(), SAI_HOSTIF_NAME_SIZE);
                                                                                              ^
Makefile:77: recipe for target 'src/obj/switch_sai_rpc_server.o' failed
```

This was introduced in [build 614](https://sonic-jenkins.westus2.cloudapp.azure.com/job/p4/job/buildimage-p4-all/614/). I'm still trying to determine which PR introduced this failure (maybe #1336?).

**Comment by jcmathews** [comment]
Issue can be resolved by adding include path starting as /sonic/path_to_saiffd_includes.
@ src/sonic-sairedis/SAI/test/saithrift/Makefile
Change to SAI_HEADER_DIR --> SAI_HEADER_DIR ?= /sonic/src/sonic-sairedis/SAI/inc
However even after building docker image, i have observed orchagent is crashing. 
A reason could be platform p4 maintains a set of SAI includes which is different from sairedis/sai_includes

**Comment by lguohan** [comment]
p4 platform is no longer maintained.
