### ISSUE TITLE
Bug:[smartswitch] db_migrator logs noisy AttributeError when migrating from 202511 image to 20241110.30 image

### ISSUE THREAD

**Issue by rameshraghupathy** [Azure/sonic-buildimage#25569]
### Is it platform specific

generic

### Importance or Severity

Medium

### Description of the bug

Problem: When downgrading from a newer SONiC image (202511) to an older image (20251110.30) using sonic-installer install <image>, db_migrator may emit repeated errors like:

Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'

config-setup: AttributeError ... version_202511_01
even when the downgrade completes and the system functions.

### Steps to Reproduce

Boot a newer image (e.g., 202511) such that VERSIONS|DATABASE:VERSION is set to a newer migration tag.

sonic-installer install <older-202411-image> and reboot into it.

Observe repeated DBMigrator has no attribute 'version_202511_01' in syslog during boot/config-setup.

### Actual Behavior and Expected Behavior

Actual Behavior: Throws errors as shown below
-rw-r----- 1 root    adm     12422604 Feb 18 15:49 syslog
root@sonic:/var/log# date
Wed Feb 18 03:49:59 PM UTC 2026
root@sonic:/var/log# grep DBMigrator syslog
2026 Feb 17 09:41:11.672609 sonic ERR db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202605_01'
2026-02-18T15:32:25.728702+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.728702+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.729177+00:00 sonic config-setup[11219]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.729177+00:00 sonic config-setup[11219]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.755595+00:00 sonic config-setup[9809]: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.755595+00:00 sonic config-setup[9809]: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.057599+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.057599+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.058090+00:00 sonic config-setup[11231]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.058090+00:00 sonic config-setup[11231]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.059064+00:00 sonic config-setup[11231]: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.059064+00:00 sonic config-setup[11231]: 'DBMigrator' object has no attribute 'version_202511_01'

Expected behavior: The above messages should not be seen

### Relevant log output

```shell
-rw-r----- 1 root    adm     12422604 Feb 18 15:49 syslog
root@sonic:/var/log# date
Wed Feb 18 03:49:59 PM UTC 2026
root@sonic:/var/log# grep DBMigrator syslog
2026 Feb 17 09:41:11.672609 sonic ERR db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202605_01'
2026-02-18T15:32:25.728702+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.728702+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.729177+00:00 sonic config-setup[11219]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.729177+00:00 sonic config-setup[11219]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.755595+00:00 sonic config-setup[9809]: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:25.755595+00:00 sonic config-setup[9809]: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.057599+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.057599+00:00 sonic db_migrator: Caught exception: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.058090+00:00 sonic config-setup[11231]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.058090+00:00 sonic config-setup[11231]: AttributeError: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.059064+00:00 sonic config-setup[11231]: 'DBMigrator' object has no attribute 'version_202511_01'
2026-02-18T15:32:26.059064+00:00 sonic config-setup[11231]: 'DBMigrator' object has no attribute 'version_202511_01'
```

### Output of `show version`, `show techsupport`

```shell
202511 Image show version output:

root@sonic:/etc/sonic# show ver | more

SONiC Software Version: SONiC.azure_cisco_202511.35941-dirty-20260205.151532
SONiC OS Version: 13
Distribution: Debian 13.3
Kernel: 6.12.41+deb13-sonic-amd64
Build commit: 58a3c8fd5
Build date: Fri Feb  6 00:17:52 UTC 2026
Built by: sonicci@sonic-ci-23-lnx.cisco.com

Platform: x86_64-8102_28fh_dpu_o-r0
HwSKU: Cisco-8102-28FH-DPU-O
ASIC: cisco-8000
ASIC Count: 1
Serial Number: FLM2820041G
Model Number: 8102-28FH-DPU-O
Hardware Revision: 0.12
Uptime: 15:23:09 up 8 days, 18:15,  1 user,  load average: 2.36, 1.95, 1.70
Date: Wed 18 Feb 2026 15:23:09

Docker images:
REPOSITORY                    TAG                                              IMAGE ID       SIZE
docker-ipxeserver-cisco       azure_cisco_202511.35941-dirty-20260205.151532   e650b61625d6   371MB
docker-ipxeserver-cisco       latest                                           e650b61625d6   371MB
docker-dhcp-relay             azure_cisco_202511.35941-dirty-20260205.151532   10d3ddff931b   274MB


20241110.30 image show version output:
admin@sonic:~$ sudo show ver | more

SONiC Software Version: SONiC.20241110.30
SONiC OS Version: 12
Distribution: Debian 12.9
Kernel: 6.1.0-29-2-amd64
Build commit: 22e31a5d4e
Build date: Wed Aug 20 21:08:48 UTC 2025
Built by: azureuser@b3c8a5a8c000002

Platform: x86_64-8102_28fh_dpu_o-r0
HwSKU: Cisco-8102-28FH-DPU-O
ASIC: cisco-8000
ASIC Count: 1
Serial Number: FLM2820041G
Model Number: 8102-28FH-DPU-O
Hardware Revision: 0.12
Uptime: 17:10:46 up  1:41,  1 user,  load average: 1.36, 1.43, 1.38
Date: Wed 18 Feb 2026 17:10:46

Docker images:
REPOSITORY                 TAG           IMAGE ID       SIZE
docker-macsec              latest        63e028fce65f   346MB
docker-orchagent           20241110.30   9716e35d5eaa   355MB
```

### Attach files (if any)

Config:    
 "VERSIONS": {
        "DATABASE": {
            "VERSION": "version_202511_01"
        }
    }

**Comment by davidm-arista** [comment]
Downgrading is not supported as the older versions don't have the objects that newer versions have.

Please close this issue, if you have no further comments.
