### PR TITLE
[sonic-yang-models]: fix unit test failure

### PR DESCRIPTION
**Pull request by lguohan**
Signed-off-by: Guohan Lu <lguohan@gmail.com>

#### Why I did it
    [sonic-yang-models]: fix unit test failure
    
    it is not quite understood why the unit test suddenly failed as below.
    but add ietf yang model explicitly to the build process fix the test
    failure.
    
    tests/test_sonic_yang_models.py .F [ 66%]
    tests/yang_model_tests/test_yang_model.py . [100%]
    Failed: pyang -f tree ./yang-models/*.yang > ./yang-models/sonic_yang_tree
    ----------------------------- Captured stderr call -----------------------------
    ./yang-models/sonic-acl.yang:8: error: module "ietf-inet-types" not found in search path
    ./yang-models/sonic-device_metadata.yang:8: error: module "ietf-yang-types" not found in search path

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by praveen-li — DISMISSED** [review]
LGTM, Thx for fixing this.

**Comment by lguohan** [comment]
seems upgrading to 2.4.0 also resolve the issue. let's use that one. I'll hold on this one.

**Comment by praveen-li** [comment]
> seems upgrading to 2.4.0 also resolve the issue. let's use that one. I'll hold on this one.

Cool, but this is highly recommend to put the search path in pyang command, so I guess we should add -p as well and list the contents of directory in case of failure, it will be easier to debug that way in future.

**Comment by dflynn-Nokia** [comment]
Upgrading to pyang 2.4.0 did not seem to fix this unit test failure when building for the marvell-armhf platform. As a test I cherry-picked this change from Gouhan's fork and I no longer see the failure. I agree that we should move forward with this PR.

**Comment by praveen-li** [comment]
> Upgrading to pyang 2.4.0 did not seem to fix this unit test failure when building for the marvell-armhf platform. As a test I cherry-picked this change from Gouhan's fork and I no longer see the failure. I agree that we should move forward with this PR.

Agree.

**Comment by joyas-joseph** [comment]
The breakage is coming from pip version 21.1.

https://github.com/mbj4668/pyang/blob/master/pyang/repository.py#L93 throws an exception with pip 21.1

**Comment by dflynn-Nokia** [comment]
@joyas-joseph I presume you are saying that this problem is related to PR #7450 which is in Draft state.
Have we confirmed that PR #7450 fixes this?

**Comment by joyas-joseph** [comment]
> @joyas-joseph I presume you are saying that this problem is related to PR #7450 which is in Draft state.
> Have we confirmed that PR #7450 fixes this?

With pip21.1, we see the below exception. The code is from pyang2.4.0 - https://github.com/mbj4668/pyang/blob/master/pyang/repository.py#L93

```
jjoseph@7dea14fc47be:/sonic/src/sonic-yang-models$ pip3 list | grep pip
pip                 21.1
jjoseph@7dea14fc47be:/sonic/src/sonic-yang-models$

jjoseph@7dea14fc47be:/sonic/src/sonic-yang-models$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
>>> import pip._internal.locations as locations
>>> location = locations.distutils_scheme('pyang')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pip._internal.locations' has no attribute 'distutils_scheme'
>>> 
```

The same code works with pip 21.0.1.

```
jjoseph@7dea14fc47be:/sonic/src/sonic-yang-models$ pip3 list | grep pip
pip                 21.0.1

jjoseph@7dea14fc47be:/sonic/src/sonic-yang-models$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
>>> import pip._internal.locations as locations
>>> location = locations.distutils_scheme('pyang')
>>> print(location)
{'purelib': '/usr/local/lib/python3.7/dist-packages', 'platlib': '/usr/local/lib/python3.7/dist-packages', 'headers': '/usr/local/include/python3.7/pyang', 'scripts': '/usr/local/bin', 'data': '/usr/local'}
>>> print(location['data'])
/usr/local
>>>
```

**Comment by dflynn-Nokia** [comment]
FWIW I have observed that a fresh build of the marvell-armhf platform on the 202012 branch succeeds.
Specifically all sonic_yang_models-1.0-py3-none-any.whl unit tests pass.
However if I perform the following sequence, I still see the sonic_yang_models-1.0-py3-none-any.whl unit test failure.

    make target/python-wheels/sonic_yang_models-1.0-py3-none-any.whl-clean
    make target/python-wheels/sonic_yang_models-1.0-py3-none-any.whl

When I cherry-pick this commit from lguohan:pyang I no longer see the unit test failure.

**Review by venkatmahalingam — APPROVED** [review]

**Comment by joyas-joseph** [comment]
Would have preferred https://github.com/Azure/sonic-buildimage/pull/7450 over this.
